package com.luis.empleado.modelo;
// Generated 14-jul-2014 18:43:38 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpleadoProyecto generated by hbm2java
 */
@Entity
@Table(name="empleado_proyecto"
    ,catalog="teide2014"
)
public class EmpleadoProyecto  implements java.io.Serializable {


     private EmpleadoProyectoId id;
     private Proyecto proyecto;
     private Empleado empleado;
     private Integer horas;

    public EmpleadoProyecto() {
    }

	
    public EmpleadoProyecto(EmpleadoProyectoId id, Proyecto proyecto, Empleado empleado) {
        this.id = id;
        this.proyecto = proyecto;
        this.empleado = empleado;
    }
    public EmpleadoProyecto(EmpleadoProyectoId id, Proyecto proyecto, Empleado empleado, Integer horas) {
       this.id = id;
       this.proyecto = proyecto;
       this.empleado = empleado;
       this.horas = horas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEmpleado", column=@Column(name="idEmpleado", nullable=false) ), 
        @AttributeOverride(name="idProyecto", column=@Column(name="idProyecto", nullable=false) ) } )
    public EmpleadoProyectoId getId() {
        return this.id;
    }
    
    public void setId(EmpleadoProyectoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProyecto", nullable=false, insertable=false, updatable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false, insertable=false, updatable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="horas")
    public Integer getHoras() {
        return this.horas;
    }
    
    public void setHoras(Integer horas) {
        this.horas = horas;
    }




}


