package com.luis.empleado.modelo;
// Generated 14-jul-2014 18:43:38 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpleadoProyectoId generated by hbm2java
 */
@Embeddable
public class EmpleadoProyectoId  implements java.io.Serializable {


     private int idEmpleado;
     private int idProyecto;

    public EmpleadoProyectoId() {
    }

    public EmpleadoProyectoId(int idEmpleado, int idProyecto) {
       this.idEmpleado = idEmpleado;
       this.idProyecto = idProyecto;
    }
   


    @Column(name="idEmpleado", nullable=false)
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }


    @Column(name="idProyecto", nullable=false)
    public int getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(int idProyecto) {
        this.idProyecto = idProyecto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoProyectoId) ) return false;
		 EmpleadoProyectoId castOther = ( EmpleadoProyectoId ) other; 
         
		 return (this.getIdEmpleado()==castOther.getIdEmpleado())
 && (this.getIdProyecto()==castOther.getIdProyecto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpleado();
         result = 37 * result + this.getIdProyecto();
         return result;
   }   


}


