package com.luis.empleado.modelo;
// Generated 14-jul-2014 18:43:38 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name="idioma"
    ,catalog="teide2014"
)
public class Idioma  implements java.io.Serializable {


     private Integer idIdioma;
     private String nombre;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Idioma() {
    }

	
    public Idioma(String nombre) {
        this.nombre = nombre;
    }
    public Idioma(String nombre, Set<Empleado> empleados) {
       this.nombre = nombre;
       this.empleados = empleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idIdioma", unique=true, nullable=false)
    public Integer getIdIdioma() {
        return this.idIdioma;
    }
    
    public void setIdIdioma(Integer idIdioma) {
        this.idIdioma = idIdioma;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="idioma_empleado", catalog="teide2014", joinColumns = { 
        @JoinColumn(name="idIdioma", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idEmpleado", nullable=false, updatable=false) })
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


